export type GalleryImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  orientation: 'portrait' | 'landscape' | 'square';
};

export const GALLERY_IMAGES: GalleryImage[] = [
  { src: '/images/gallery-extra/ger-and-land-cruiser-rain.jpg', alt: 'Ger and Land Cruiser in the rain', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/gallery-extra/horseman-under-larch-trees.jpg', alt: 'Horseman under larch trees', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/gallery-extra/horses-and-child-by-lake.jpg', alt: 'Child walking past horses beside the lake', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/gallery-extra/horses-in-forest-rain.jpg', alt: 'Pack horses resting in the forest rain', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/packed-horses-rain-camp.jpg', alt: 'Packed horses waiting under storm clouds', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/rain-jacket-valley-view.jpg', alt: 'Rain jacket view across the valley', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/rainy-horseback-overlook.jpg', alt: 'Rainy horseback overlook above the valley', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/rearing-horse-over-valley.jpg', alt: 'Horse rearing above the valley', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/rider-mountain-clouds.jpg', alt: 'Rider and horse below mountain clouds', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/gallery-extra/rider-rearing-horse-wide.jpg', alt: 'Rider on a rearing horse against the sky', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/expedition-originals/eagle-black-white-portrait.jpg', alt: 'Black and white portrait of a Mongolian eagle', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/ger-and-van-camp-wide.jpg', alt: 'Ger and van camp beneath the mountains', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/expedition-originals/ger-blue-hour-original.jpg', alt: 'Ger at blue hour beneath the mountains', width: 1600, height: 1066, orientation: 'landscape' },
  { src: '/images/expedition-originals/ger-sunrise-original.jpg', alt: 'Ger at sunrise in the valley', width: 1600, height: 1066, orientation: 'landscape' },
  { src: '/images/expedition-originals/ger-sunset-wide-original.jpg', alt: 'Wide ger camp sunset', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/expedition-originals/ger-with-sun-original.jpg', alt: 'Ger with low sun over the valley', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/expedition-originals/ger-yaks-van-portrait.jpg', alt: 'Ger camp with yaks and van in the valley', width: 966, height: 1448, orientation: 'portrait' },
  { src: '/images/expedition-originals/grazing-horse-river-sun-portrait.jpg', alt: 'Horse grazing beside a sunlit river', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/horseman-valley-lookout-portrait.jpg', alt: 'Horseman looking across the Orkhon Valley', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/layered-hills-sunset-wide.jpg', alt: 'Layered hills at sunset', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/expedition-originals/motorbike-valley-dusk-portrait.jpg', alt: 'Motorbike above the valley at dusk', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/motorbike-valley-repair-portrait.jpg', alt: 'Motorbike stop overlooking a broad valley', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/mountain-sunset-river-wide.jpg', alt: 'Mountain sunset above a winding river', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/expedition-originals/orkhon-valley-sunset-wide.jpg', alt: 'Sunset over the Orkhon Valley river bends', width: 1620, height: 1080, orientation: 'landscape' },
  { src: '/images/expedition-originals/rider-storm-valley-panorama-portrait.jpg', alt: 'Rider under dramatic storm clouds in the valley', width: 1536, height: 2048, orientation: 'portrait' },
  { src: '/images/expedition-originals/river-horseman-silhouette-portrait.jpg', alt: 'Horseman silhouetted beside the river', width: 1036, height: 1439, orientation: 'portrait' },
  { src: '/images/expedition-originals/saddle-valley-black-white-portrait.jpg', alt: 'Black and white saddle view over the valley', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/storm-cloud-valley-panorama.jpg', alt: 'Panoramic storm clouds over the valley', width: 2048, height: 1536, orientation: 'landscape' },
  { src: '/images/expedition-originals/suma-horse-black-white-portrait.jpg', alt: 'Suma standing with a horse in black and white', width: 997, height: 1496, orientation: 'portrait' },
  { src: '/images/expedition-originals/suma-motorbike-field-portrait.jpg', alt: 'Suma on a motorbike in the open field', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/suma-river-crossing-original.jpg', alt: 'Suma riding through a shallow river crossing', width: 1200, height: 1600, orientation: 'portrait' },
  { src: '/images/expedition-originals/van-river-sunset-portrait.jpg', alt: 'Van parked below a glowing river sunset', width: 1536, height: 2048, orientation: 'portrait' },
  { src: '/images/expedition-originals/van-valley-road-portrait.jpg', alt: 'White van crossing a remote valley road', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/expedition-originals/yaks-river-backlit-portrait.jpg', alt: 'Yaks grazing beside the river in backlit evening sun', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/eagle-portrait-original.jpg', alt: 'Close portrait of a Mongolian eagle', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/family.jpg', alt: 'Host family life in the valley', width: 1140, height: 822, orientation: 'landscape' },
  { src: '/images/ger-camp-yaks-portrait.jpg', alt: 'Gers and grazing yaks in the valley', width: 966, height: 1448, orientation: 'portrait' },
  { src: '/images/ger-interior.jpg', alt: 'Inside a traditional ger', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/gers2.jpg', alt: 'Traditional gers in open country', width: 2000, height: 1500, orientation: 'landscape' },
  { src: '/images/guide-horse-portrait.jpg', alt: 'Suma standing with his horse on the open steppe', width: 997, height: 1496, orientation: 'portrait' },
  { src: '/images/guide.jpg', alt: 'Suma, local horseman and guide', width: 1152, height: 2048, orientation: 'portrait' },
  { src: '/images/herder-valley-portrait.jpg', alt: 'Horseman watching over the valley and grazing herd', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/hero-sunset-valley.jpg', alt: 'Sunset over the Orkhon Valley river', width: 2400, height: 1600, orientation: 'landscape' },
  { src: '/images/hero.jpg', alt: 'Horseback riding across the Mongolian steppe', width: 2400, height: 1800, orientation: 'landscape' },
  { src: '/images/lake.jpg', alt: 'Eight Lakes valley and water', width: 1200, height: 1600, orientation: 'portrait' },
  { src: '/images/landscape2.jpg', alt: 'Open Mongolian landscape', width: 1200, height: 900, orientation: 'landscape' },
  { src: '/images/mosaic1.jpg', alt: 'Traditional gers with grazing animals', width: 1200, height: 900, orientation: 'landscape' },
  { src: '/images/mosaic2.jpg', alt: 'Ger camp at sunrise in the valley', width: 1200, height: 900, orientation: 'landscape' },
  { src: '/images/mosaic3.jpg', alt: 'Mongolian eagle portrait', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/mosaic4.jpg', alt: 'Wide sunset view across the Orkhon Valley', width: 1200, height: 900, orientation: 'landscape' },
  { src: '/images/mosaic5.jpg', alt: 'Ger silhouette at dusk', width: 1200, height: 900, orientation: 'landscape' },
  { src: '/images/partnership2.jpg', alt: 'Local hosts and horses in the valley', width: 1000, height: 912, orientation: 'landscape' },
  { src: '/images/riding2.jpg', alt: 'Rider crossing shallow water on horseback', width: 1200, height: 900, orientation: 'landscape' },
  { src: '/images/riding3.jpg', alt: 'Grazing animals beside the river', width: 1200, height: 900, orientation: 'landscape' },
  { src: '/images/rob-family.jpg', alt: 'Robert with Ganbold, Suma and family', width: 1042, height: 712, orientation: 'landscape' },
  { src: '/images/rob-zaher.jpg', alt: 'Robert Zaher in Mongolia', width: 768, height: 1024, orientation: 'portrait' },
  { src: '/images/saddle-valley-portrait.jpg', alt: 'Saddled horse looking out over the valley', width: 1080, height: 1620, orientation: 'portrait' },
  { src: '/images/testimonial-fin-bennet.jpg', alt: 'Fin with children beside a ger', width: 1400, height: 1050, orientation: 'landscape' },
  { src: '/images/testimonial-irik-clawson.jpg', alt: 'Irik riding at sunset', width: 1024, height: 768, orientation: 'landscape' },
]
